[package]
name = "linkmap"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
reqwest = "0.12.23"
scraper = "0.24.0"
url = "2.5.7"
